# Generated by Django 5.2.1 on 2025-05-31 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OJ', '0003_topic_problemset'),
    ]

    operations = [
        migrations.AddField(
            model_name='problemset',
            name='expected_output',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='problemset',
            name='input_data',
            field=models.TextField(default=''),
        ),
    ]
