# Generated by Django 5.2.1 on 2025-06-05 08:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OJ', '0004_problemset_expected_output_problemset_input_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='codesubmission',
            name='problem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='OJ.problemset'),
        ),
    ]
